name: screen_capture_event_example
description: Demonstrates how to use the screen_capture_event plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  screen_capture_event:
    path: ../
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true 